version: '3'

services:
  world:
    build:
      context: .
      args:
        TZ: America/Lima
        TERRAFORM_INSTALL_VERSION: "0.13.5"
        PACKER_INSTALL_VERSION: "1.5.6"
    image: practica-aws
    container_name: practica-aws
    stdin_open: true
    tty: true
    volumes:
      - ./practica:/app
